stored procedures: add required includes
I'm getting the following while building the stored procedures:

order_status.c: In function 'order_status':
order_status.c:123: error: 'textout' undeclared (first use in this function)

- looks like we need the utils/builtins.h header for textout.

Signed-off-by: Jeremy Kerr <jk@ozlabs.org>